#==========================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# 删除旧版本和工作流程运行
#==========================================================================

name: 删除旧版本和工作流程运行

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      delete_releases:
        description: "删除 Releases 文件?"
        required: false
        default: false
        type: boolean
      delete_tags:
        description: "删除相关标签?"
        required: false
        default: false
        type: boolean
      prerelease_option:
        description: "是否区分预发布."
        required: false
        default: "all"
        type: choice
        options:
          - all
          - true
          - false
      releases_keep_latest:
        description: "要保留多少个最新版本."
        required: false
        default: "2"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      releases_keep_keyword:
        description: "保留版本的关键字."
        required: false
        default: "v0/_save_/kernel_"
      delete_workflows:
        description: "删除工作流记录?"
        required: true
        default: true
        type: boolean
      workflows_keep_day:
        description: "保留工作流程的天数."
        required: false
        default: "1"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      workflows_keep_keyword:
        description: "保持工作流程的关键字."
        required: false
        default: ""
      out_log:
        description: "输出详细的 JSON 日志."
        required: false
        default: true
        type: boolean

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 初始化环境
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 删除发布和工作流程运行
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: ${{ inputs.delete_releases }}
          delete_tags: ${{ inputs.delete_tags }}
          prerelease_option: ${{ inputs.prerelease_option }}
          releases_keep_latest: ${{ inputs.releases_keep_latest }}
          releases_keep_keyword: ${{ inputs.releases_keep_keyword }}
          delete_workflows: ${{ inputs.delete_workflows }}
          workflows_keep_day: ${{ inputs.workflows_keep_day }}
          workflows_keep_keyword: ${{ inputs.workflows_keep_keyword }}
          out_log: ${{ inputs.out_log }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
